#Code that sends out the email

from Google import Create_Service
import base64
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

credentials_File = 'credientials.json' #This is the file generated by google, it's basically the API key
gmail = 'gmail'  #API type
version = 'v1'
scope = ['https://mail.google.com/']

service = Create_Service(credentials_File, gmail, version, scope)

label_body = {
'removeLabelIds': ['IMPORTANT', 'CATEGORY_UPDATES', 'INBOX'],
'addLabelIds': ['Label_3']
}

emailMsg = 'You Have a Maintenance Window Scheduled'
mimeMessage = MIMEMultipart()
mimeMessage['to'] = 'jadasardin@gmail.com'
mimeMessage['subject'] = 'Maintenance Window'
mimeMessage.attach(MIMEText(emailMsg, 'plain'))
raw_string = base64.urlsafe_b64encode(mimeMessage.as_bytes()).decode()

message = service.users().messages().send(userId='me', body={'raw': raw_string}).execute()
print(message)